name: Compile LaTeX and Deploy to GitHub Pages

on:
  push:
    branches:
      - main
  pull_request:

permissions:
  id-token: write  
  contents: write   

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up TeX Live
      run: |
        sudo apt-get update && sudo apt-get install -y texlive-latex-base texlive-latex-extra texlive-fonts-recommended

       
    - name: Compile .tex files to .pdf
      run: |
        mkdir -p output
        find . -name "*.tex" | while read file; do
        pdflatex -interaction=nonstopmode --output-directory=output "$file"
        pdflatex -interaction=nonstopmode --output-directory=output "$file"
        done

    - name: Generate HTML index with Python
      run: |
        python3 .github/workflows/generate_html.py

    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: prova
        path: "./output"

  deploy:
    runs-on: ubuntu-latest
    needs: build

    permissions:
      pages: write      
      id-token: write   

    # Deploy to the github-pages environment
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
    - name: Download artifacts
      uses: actions/download-artifact@v4
      with:
        name: prova
    - name: Upload artifact
      uses: actions/upload-pages-artifact@v3
      with:
        path: "."
    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v4
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./output